# fly.toml app configuration file generated for blazingly-fast-support on 2024-01-07T10:38:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blazingly-fast-support"
primary_region = "eze"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
